CREATE TABLE dbo.Roles
	(
	Id int NOT NULL IDENTITY (1, 1),
	Name varchar(50) NOT NULL
	)  ON [PRIMARY]

ALTER TABLE dbo.Roles ADD CONSTRAINT
	PK_Roles PRIMARY KEY CLUSTERED 
	(
	Id
	) WITH( STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
