CREATE TABLE dbo.Users
	(
	Id int NOT NULL IDENTITY (1, 1),
	Username varchar(15) NOT NULL,
	Password varchar(255) NOT NULL,
	Email varchar(255) NOT NULL,
	RoleId int NOT NULL
	)  ON [PRIMARY]

ALTER TABLE dbo.Users ADD CONSTRAINT
	PK_Users PRIMARY KEY CLUSTERED 
	(
	Id
	) WITH( STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
